schema_version = "1.0.0"
id = "list_organizer"
version = "1.41.10"
name = "List Organizer"
tagline = "Organize vertex groups and shape keys"
maintainer = "LingQS"
website = "https://github.com/Ling-QS/blender_list_organizer"
type = "add-on"
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["User Interface"]
